/* Migration script for 5.2.0 */
/*  generated script start */

/*
Deployment script for Usercube520

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/
/*
Deployment script for UsercubeV5Demo

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/


ALTER TABLE "UC_EntityPropertyMappings" ADD "UniqueKeyOrder" INT NULL;
GO

Update m set m."UniqueKeyOrder"=rnumber-1 FROM "UC_EntityPropertyMappings" m
JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY entitytype_id ORDER BY ep.entitytype_id, ep.id ) as rnumber, ep.id from Uc_EntityPropertymappings epm join UM_EntityProperties ep on ep.id = epm.id where IsUniqueKey=1)e on e.id=m.id
 

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
PRINT N'Dropping [dbo].[DF_Resources_ValidFrom]...';


GO
ALTER TABLE [dbo].[UR_Resources] DROP CONSTRAINT [DF_Resources_ValidFrom];


GO
PRINT N'Dropping [dbo].[DF_Resources_ValidTo]...';


GO
ALTER TABLE [dbo].[UR_Resources] DROP CONSTRAINT [DF_Resources_ValidTo];


GO
PRINT N'Dropping [dbo].[DF_Resources_Dirty]...';


GO
ALTER TABLE [dbo].[UR_Resources] DROP CONSTRAINT [DF_Resources_Dirty];


GO
PRINT N'Dropping [dbo].[FK_ResourceChanges_Type]...';


GO
ALTER TABLE [dbo].[UR_ResourceChanges] DROP CONSTRAINT [FK_ResourceChanges_Type];


GO
PRINT N'Dropping [dbo].[FK_Resources_Type]...';


GO
ALTER TABLE [dbo].[UR_Resources] DROP CONSTRAINT [FK_Resources_Type];


GO
PRINT N'Starting rebuilding table [dbo].[UR_ResourceChanges]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UR_ResourceChanges] (
    [JobInstanceId]   BIGINT          NOT NULL,
    [ChangeOperation] INT             NOT NULL,
    [Resource_Id]     BIGINT          NOT NULL,
    [Type]            BIGINT          NOT NULL,
    [ValidFrom]       DATETIME2 (2)   NULL,
    [ValidTo]         DATETIME2 (2)   NULL,
    [DisplayName_L1]  NVARCHAR (442)  NULL,
    [PrimaryKey]      NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U0]              NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U1]              NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U2]              NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [C0]              NVARCHAR (4000) NULL,
    [C1]              NVARCHAR (4000) NULL,
    [C2]              NVARCHAR (4000) NULL,
    [C3]              NVARCHAR (4000) NULL,
    [C4]              NVARCHAR (442)  NULL,
    [C5]              NVARCHAR (442)  NULL,
    [C6]              NVARCHAR (442)  NULL,
    [C7]              NVARCHAR (442)  NULL,
    [C8]              NVARCHAR (442)  NULL,
    [C9]              NVARCHAR (442)  NULL,
    [CA]              NVARCHAR (442)  NULL,
    [CB]              NVARCHAR (442)  NULL,
    [CC]              NVARCHAR (442)  NULL,
    [CD]              NVARCHAR (442)  NULL,
    [CE]              NVARCHAR (442)  NULL,
    [R0] NVARCHAR(442) COLLATE Latin1_General_BIN2 NULL,
    [DisplayName_L2]  NVARCHAR (442)  NULL,
    [I40]             BIGINT          NULL,
    [I41]             BIGINT          NULL,
    [I42]             BIGINT          NULL,
    [I43]             BIGINT          NULL,
    [I44]             BIGINT          NULL,
    [CF]              NVARCHAR (442)  NULL,
    [CG]              NVARCHAR (442)  NULL,
    [CH]              NVARCHAR (442)  NULL,
    [CI]              NVARCHAR (442)  NULL,
    [CJ]              NVARCHAR (442)  NULL,
    [CK]              NVARCHAR (442)  NULL,
    [CL]              NVARCHAR (442)  NULL,
    [CM]              NVARCHAR (442)  NULL,
    [CN]              NVARCHAR (442)  NULL,
    [CO]              NVARCHAR (442)  NULL,
    [CP]              NVARCHAR (442)  NULL,
    [CQ]              NVARCHAR (442)  NULL,
    [CR]              NVARCHAR (442)  NULL,
    [CS]              NVARCHAR (442)  NULL,
    [CT]              NVARCHAR (442)  NULL,
    [DisplayName_L3]  NVARCHAR (442)  NULL,
    [I45]             BIGINT          NULL,
    [I46]             BIGINT          NULL,
    [I47]             BIGINT          NULL,
    [I48]             BIGINT          NULL,
    [I49]             BIGINT          NULL,
    [CU]              NVARCHAR (442)  NULL,
    [CV]              NVARCHAR (442)  NULL,
    [C10]             NVARCHAR (442)  NULL,
    [C11]             NVARCHAR (442)  NULL,
    [C12]             NVARCHAR (442)  NULL,
    [C13]             NVARCHAR (442)  NULL,
    [C14]             NVARCHAR (442)  NULL,
    [C15]             NVARCHAR (442)  NULL,
    [C16]             NVARCHAR (442)  NULL,
    [C17]             NVARCHAR (442)  NULL,
    [C18]             NVARCHAR (442)  NULL,
    [C19]             NVARCHAR (442)  NULL,
    [C1A]             NVARCHAR (442)  NULL,
    [C1B]             NVARCHAR (442)  NULL,
    [C1C]             NVARCHAR (442)  NULL,
    [DisplayName_L4]  NVARCHAR (442)  NULL,
    [I4A]             BIGINT          NULL,
    [I4B]             BIGINT          NULL,
    [I4C]             BIGINT          NULL,
    [I4D]             BIGINT          NULL,
    [I4E]             BIGINT          NULL,
    [C1D]             NVARCHAR (442)  NULL,
    [C1E]             NVARCHAR (442)  NULL,
    [C1F]             NVARCHAR (442)  NULL,
    [C1G]             NVARCHAR (442)  NULL,
    [C1H]             NVARCHAR (442)  NULL,
    [C1I]             NVARCHAR (442)  NULL,
    [C1J]             NVARCHAR (442)  NULL,
    [C1K]             NVARCHAR (442)  NULL,
    [C1L]             NVARCHAR (442)  NULL,
    [C1M]             NVARCHAR (442)  NULL,
    [C1N]             NVARCHAR (442)  NULL,
    [C1O]             NVARCHAR (442)  NULL,
    [C1P]             NVARCHAR (442)  NULL,
    [C1Q]             NVARCHAR (442)  NULL,
    [C1R]             NVARCHAR (442)  NULL,
    [DisplayName_L5]  NVARCHAR (442)  NULL,
    [I4F]             BIGINT          NULL,
    [I4G]             BIGINT          NULL,
    [I4H]             BIGINT          NULL,
    [I4I]             BIGINT          NULL,
    [C1S]             NVARCHAR (442)  NULL,
    [C1T]             NVARCHAR (442)  NULL,
    [C1U]             NVARCHAR (442)  NULL,
    [C1V]             NVARCHAR (442)  NULL,
    [C20]             NVARCHAR (442)  NULL,
    [C21]             NVARCHAR (442)  NULL,
    [C22]             NVARCHAR (442)  NULL,
    [C23]             NVARCHAR (442)  NULL,
    [C24]             NVARCHAR (442)  NULL,
    [C25]             NVARCHAR (442)  NULL,
    [C26]             NVARCHAR (442)  NULL,
    [C27]             NVARCHAR (442)  NULL,
    [C28]             NVARCHAR (442)  NULL,
    [C29]             NVARCHAR (442)  NULL,
    [C2A]             NVARCHAR (442)  NULL,
    [DisplayName_L6]  NVARCHAR (442)  NULL,
    [I4J]             BIGINT          NULL,
    [I4K]             BIGINT          NULL,
    [I4L]             BIGINT          NULL,
    [C2B]             NVARCHAR (442)  NULL,
    [C2C]             NVARCHAR (442)  NULL,
    [C2D]             NVARCHAR (442)  NULL,
    [C2E]             NVARCHAR (442)  NULL,
    [C2F]             NVARCHAR (442)  NULL,
    [C2G]             NVARCHAR (442)  NULL,
    [C2H]             NVARCHAR (442)  NULL,
    [C2I]             NVARCHAR (442)  NULL,
    [C2J]             NVARCHAR (442)  NULL,
    [C2K]             NVARCHAR (442)  NULL,
    [C2L]             NVARCHAR (442)  NULL,
    [C2M]             NVARCHAR (442)  NULL,
    [C2N]             NVARCHAR (442)  NULL,
    [DisplayName_L7]  NVARCHAR (442)  NULL,
    [I4M]             BIGINT          NULL,
    [I4N]             BIGINT          NULL,
    [C2O]             NVARCHAR (442)  NULL,
    [C2P]             NVARCHAR (442)  NULL,
    [C2Q]             NVARCHAR (442)  NULL,
    [C2R]             NVARCHAR (442)  NULL,
    [C2S]             NVARCHAR (442)  NULL,
    [C2T]             NVARCHAR (442)  NULL,
    [C2U]             NVARCHAR (442)  NULL,
    [C2V]             NVARCHAR (442)  NULL,
    [C30]             NVARCHAR (442)  NULL,
    [C31]             NVARCHAR (442)  NULL,
    [C32]             NVARCHAR (442)  NULL,
    [C33]             NVARCHAR (442)  NULL,
    [C34]             NVARCHAR (442)  NULL,
    [C35]             NVARCHAR (442)  NULL,
    [C36]             NVARCHAR (442)  NULL,
    [DisplayName_L8]  NVARCHAR (442)  NULL,
    [I4O]             BIGINT          NULL,
    [C37]             NVARCHAR (442)  NULL,
    [C38]             NVARCHAR (442)  NULL,
    [C39]             NVARCHAR (442)  NULL,
    [C3A]             NVARCHAR (442)  NULL,
    [C3B]             NVARCHAR (442)  NULL,
    [C3C]             NVARCHAR (442)  NULL,
    [C3D]             NVARCHAR (442)  NULL,
    [C3E]             NVARCHAR (442)  NULL,
    [C3F]             NVARCHAR (442)  NULL,
    [C3G]             NVARCHAR (442)  NULL,
    [C3H]             NVARCHAR (442)  NULL,
    [C3I]             NVARCHAR (442)  NULL,
    [C3J]             NVARCHAR (442)  NULL,
    [C3K]             NVARCHAR (442)  NULL,
    [C3L]             NVARCHAR (442)  NULL,
    [C3M]             NVARCHAR (442)  NULL,
    [C3N]             NVARCHAR (442)  NULL,
    [C3O]             NVARCHAR (442)  NULL,
    [C3P]             NVARCHAR (442)  NULL,
    [C3Q]             NVARCHAR (442)  NULL,
    [C3R]             NVARCHAR (442)  NULL,
    [C3S]             NVARCHAR (442)  NULL,
    [C3T]             NVARCHAR (442)  NULL,
    [C3U]             NVARCHAR (442)  NULL,
    [C3V]             NVARCHAR (442)  NULL
);

CREATE CLUSTERED INDEX [tmp_ms_xx_index_IX_ResourceChanges1]
    ON [dbo].[tmp_ms_xx_UR_ResourceChanges]([JobInstanceId] ASC, [Type] ASC, [PrimaryKey] ASC, [Resource_Id] ASC);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UR_ResourceChanges])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_UR_ResourceChanges] ([JobInstanceId], [Type], [Resource_Id], [ChangeOperation], [ValidFrom], [ValidTo], [DisplayName_L1], [C0], [C1], [C2], [C3], [C4], [C5], [C6], [C7], [C8], [C9], [CA], [CB], [CC], [CD], [CE], [DisplayName_L2], [I40], [I41], [I42], [I43], [I44], [CF], [CG], [CH], [CI], [CJ], [CK], [CL], [CM], [CN], [CO], [CP], [CQ], [CR], [CS], [CT], [DisplayName_L3], [I45], [I46], [I47], [I48], [I49], [CU], [CV], [C10], [C11], [C12], [C13], [C14], [C15], [C16], [C17], [C18], [C19], [C1A], [C1B], [C1C], [DisplayName_L4], [I4A], [I4B], [I4C], [I4D], [I4E], [C1D], [C1E], [C1F], [C1G], [C1H], [C1I], [C1J], [C1K], [C1L], [C1M], [C1N], [C1O], [C1P], [C1Q], [C1R], [DisplayName_L5], [I4F], [I4G], [I4H], [I4I], [C1S], [C1T], [C1U], [C1V], [C20], [C21], [C22], [C23], [C24], [C25], [C26], [C27], [C28], [C29], [C2A], [DisplayName_L6], [I4J], [I4K], [I4L], [C2B], [C2C], [C2D], [C2E], [C2F], [C2G], [C2H], [C2I], [C2J], [C2K], [C2L], [C2M], [C2N], [DisplayName_L7], [I4M], [I4N], [C2O], [C2P], [C2Q], [C2R], [C2S], [C2T], [C2U], [C2V], [C30], [C31], [C32], [C33], [C34], [C35], [C36], [DisplayName_L8], [I4O], [C37], [C38], [C39], [C3A], [C3B], [C3C], [C3D], [C3E], [C3F], [C3G], [C3H], [C3I], [C3J], [C3K], [C3L], [C3M], [C3N], [C3O], [C3P], [C3Q], [C3R], [C3S], [C3T], [C3U], [C3V])
        SELECT   [JobInstanceId],
                 [Type],
                 [Resource_Id],
                 [ChangeOperation],
                 [ValidFrom],
                 [ValidTo],
                 [DisplayName_L1],
                 [C0],
                 [C1],
                 [C2],
                 [C3],
                 [C4],
                 [C5],
                 [C6],
                 [C7],
                 [C8],
                 [C9],
                 [CA],
                 [CB],
                 [CC],
                 [CD],
                 [CE],
                 [DisplayName_L2],
                 [I40],
                 [I41],
                 [I42],
                 [I43],
                 [I44],
                 [CF],
                 [CG],
                 [CH],
                 [CI],
                 [CJ],
                 [CK],
                 [CL],
                 [CM],
                 [CN],
                 [CO],
                 [CP],
                 [CQ],
                 [CR],
                 [CS],
                 [CT],
                 [DisplayName_L3],
                 [I45],
                 [I46],
                 [I47],
                 [I48],
                 [I49],
                 [CU],
                 [CV],
                 [C10],
                 [C11],
                 [C12],
                 [C13],
                 [C14],
                 [C15],
                 [C16],
                 [C17],
                 [C18],
                 [C19],
                 [C1A],
                 [C1B],
                 [C1C],
                 [DisplayName_L4],
                 [I4A],
                 [I4B],
                 [I4C],
                 [I4D],
                 [I4E],
                 [C1D],
                 [C1E],
                 [C1F],
                 [C1G],
                 [C1H],
                 [C1I],
                 [C1J],
                 [C1K],
                 [C1L],
                 [C1M],
                 [C1N],
                 [C1O],
                 [C1P],
                 [C1Q],
                 [C1R],
                 [DisplayName_L5],
                 [I4F],
                 [I4G],
                 [I4H],
                 [I4I],
                 [C1S],
                 [C1T],
                 [C1U],
                 [C1V],
                 [C20],
                 [C21],
                 [C22],
                 [C23],
                 [C24],
                 [C25],
                 [C26],
                 [C27],
                 [C28],
                 [C29],
                 [C2A],
                 [DisplayName_L6],
                 [I4J],
                 [I4K],
                 [I4L],
                 [C2B],
                 [C2C],
                 [C2D],
                 [C2E],
                 [C2F],
                 [C2G],
                 [C2H],
                 [C2I],
                 [C2J],
                 [C2K],
                 [C2L],
                 [C2M],
                 [C2N],
                 [DisplayName_L7],
                 [I4M],
                 [I4N],
                 [C2O],
                 [C2P],
                 [C2Q],
                 [C2R],
                 [C2S],
                 [C2T],
                 [C2U],
                 [C2V],
                 [C30],
                 [C31],
                 [C32],
                 [C33],
                 [C34],
                 [C35],
                 [C36],
                 [DisplayName_L8],
                 [I4O],
                 [C37],
                 [C38],
                 [C39],
                 [C3A],
                 [C3B],
                 [C3C],
                 [C3D],
                 [C3E],
                 [C3F],
                 [C3G],
                 [C3H],
                 [C3I],
                 [C3J],
                 [C3K],
                 [C3L],
                 [C3M],
                 [C3N],
                 [C3O],
                 [C3P],
                 [C3Q],
                 [C3R],
                 [C3S],
                 [C3T],
                 [C3U],
                 [C3V]
        FROM     [dbo].[UR_ResourceChanges]
        ORDER BY [JobInstanceId] ASC, [Type] ASC, [Resource_Id] ASC;
    END

DROP TABLE [dbo].[UR_ResourceChanges];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UR_ResourceChanges]', N'UR_ResourceChanges';

EXECUTE sp_rename N'[dbo].[UR_ResourceChanges].[tmp_ms_xx_index_IX_ResourceChanges1]', N'IX_ResourceChanges', N'INDEX';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UR_Resources] (
    [Id]             BIGINT          NOT NULL,
    [Type]           BIGINT          NOT NULL,
    [ValidFrom]      DATETIME2 (2)   CONSTRAINT [DF_Resources_ValidFrom] DEFAULT GETUTCDATE() NOT NULL,
    [ValidTo]        DATETIME2 (2)   CONSTRAINT [DF_Resources_ValidTo] DEFAULT (CONVERT (DATETIME2 (2), '9999-12-31 23:59:59.999', 121)) NOT NULL,
    [Dirty]          BIT             CONSTRAINT [DF_Resources_Dirty] DEFAULT ((0)) NOT NULL,
    [DisplayName_L1] NVARCHAR (442)  NULL,
    [PrimaryKey]     NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U0]             NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U1]             NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U2]             NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [C0]             NVARCHAR (4000) NULL,
    [C1]             NVARCHAR (4000) NULL,
    [C2]             NVARCHAR (4000) NULL,
    [C3]             NVARCHAR (4000) NULL,
    [C4]             NVARCHAR (442)  NULL,
    [C5]             NVARCHAR (442)  NULL,
    [C6]             NVARCHAR (442)  NULL,
    [C7]             NVARCHAR (442)  NULL,
    [C8]             NVARCHAR (442)  NULL,
    [C9]             NVARCHAR (442)  NULL,
    [CA]             NVARCHAR (442)  NULL,
    [CB]             NVARCHAR (442)  NULL,
    [CC]             NVARCHAR (442)  NULL,
    [CD]             NVARCHAR (442)  NULL,
    [CE]             NVARCHAR (442)  NULL,
    [R0] NVARCHAR(442) COLLATE Latin1_General_BIN2 NULL,
    [DisplayName_L2] NVARCHAR (442)  NULL,
    [I40]            BIGINT          NULL,
    [I41]            BIGINT          NULL,
    [I42]            BIGINT          NULL,
    [I43]            BIGINT          NULL,
    [I44]            BIGINT          NULL,
    [CF]             NVARCHAR (442)  NULL,
    [CG]             NVARCHAR (442)  NULL,
    [CH]             NVARCHAR (442)  NULL,
    [CI]             NVARCHAR (442)  NULL,
    [CJ]             NVARCHAR (442)  NULL,
    [CK]             NVARCHAR (442)  NULL,
    [CL]             NVARCHAR (442)  NULL,
    [CM]             NVARCHAR (442)  NULL,
    [CN]             NVARCHAR (442)  NULL,
    [CO]             NVARCHAR (442)  NULL,
    [CP]             NVARCHAR (442)  NULL,
    [CQ]             NVARCHAR (442)  NULL,
    [CR]             NVARCHAR (442)  NULL,
    [CS]             NVARCHAR (442)  NULL,
    [CT]             NVARCHAR (442)  NULL,
    [DisplayName_L3] NVARCHAR (442)  NULL,
    [I45]            BIGINT          NULL,
    [I46]            BIGINT          NULL,
    [I47]            BIGINT          NULL,
    [I48]            BIGINT          NULL,
    [I49]            BIGINT          NULL,
    [CU]             NVARCHAR (442)  NULL,
    [CV]             NVARCHAR (442)  NULL,
    [C10]            NVARCHAR (442)  NULL,
    [C11]            NVARCHAR (442)  NULL,
    [C12]            NVARCHAR (442)  NULL,
    [C13]            NVARCHAR (442)  NULL,
    [C14]            NVARCHAR (442)  NULL,
    [C15]            NVARCHAR (442)  NULL,
    [C16]            NVARCHAR (442)  NULL,
    [C17]            NVARCHAR (442)  NULL,
    [C18]            NVARCHAR (442)  NULL,
    [C19]            NVARCHAR (442)  NULL,
    [C1A]            NVARCHAR (442)  NULL,
    [C1B]            NVARCHAR (442)  NULL,
    [C1C]            NVARCHAR (442)  NULL,
    [DisplayName_L4] NVARCHAR (442)  NULL,
    [I4A]            BIGINT          NULL,
    [I4B]            BIGINT          NULL,
    [I4C]            BIGINT          NULL,
    [I4D]            BIGINT          NULL,
    [I4E]            BIGINT          NULL,
    [C1D]            NVARCHAR (442)  NULL,
    [C1E]            NVARCHAR (442)  NULL,
    [C1F]            NVARCHAR (442)  NULL,
    [C1G]            NVARCHAR (442)  NULL,
    [C1H]            NVARCHAR (442)  NULL,
    [C1I]            NVARCHAR (442)  NULL,
    [C1J]            NVARCHAR (442)  NULL,
    [C1K]            NVARCHAR (442)  NULL,
    [C1L]            NVARCHAR (442)  NULL,
    [C1M]            NVARCHAR (442)  NULL,
    [C1N]            NVARCHAR (442)  NULL,
    [C1O]            NVARCHAR (442)  NULL,
    [C1P]            NVARCHAR (442)  NULL,
    [C1Q]            NVARCHAR (442)  NULL,
    [C1R]            NVARCHAR (442)  NULL,
    [DisplayName_L5] NVARCHAR (442)  NULL,
    [I4F]            BIGINT          NULL,
    [I4G]            BIGINT          NULL,
    [I4H]            BIGINT          NULL,
    [I4I]            BIGINT          NULL,
    [C1S]            NVARCHAR (442)  NULL,
    [C1T]            NVARCHAR (442)  NULL,
    [C1U]            NVARCHAR (442)  NULL,
    [C1V]            NVARCHAR (442)  NULL,
    [C20]            NVARCHAR (442)  NULL,
    [C21]            NVARCHAR (442)  NULL,
    [C22]            NVARCHAR (442)  NULL,
    [C23]            NVARCHAR (442)  NULL,
    [C24]            NVARCHAR (442)  NULL,
    [C25]            NVARCHAR (442)  NULL,
    [C26]            NVARCHAR (442)  NULL,
    [C27]            NVARCHAR (442)  NULL,
    [C28]            NVARCHAR (442)  NULL,
    [C29]            NVARCHAR (442)  NULL,
    [C2A]            NVARCHAR (442)  NULL,
    [DisplayName_L6] NVARCHAR (442)  NULL,
    [I4J]            BIGINT          NULL,
    [I4K]            BIGINT          NULL,
    [I4L]            BIGINT          NULL,
    [C2B]            NVARCHAR (442)  NULL,
    [C2C]            NVARCHAR (442)  NULL,
    [C2D]            NVARCHAR (442)  NULL,
    [C2E]            NVARCHAR (442)  NULL,
    [C2F]            NVARCHAR (442)  NULL,
    [C2G]            NVARCHAR (442)  NULL,
    [C2H]            NVARCHAR (442)  NULL,
    [C2I]            NVARCHAR (442)  NULL,
    [C2J]            NVARCHAR (442)  NULL,
    [C2K]            NVARCHAR (442)  NULL,
    [C2L]            NVARCHAR (442)  NULL,
    [C2M]            NVARCHAR (442)  NULL,
    [C2N]            NVARCHAR (442)  NULL,
    [DisplayName_L7] NVARCHAR (442)  NULL,
    [I4M]            BIGINT          NULL,
    [I4N]            BIGINT          NULL,
    [C2O]            NVARCHAR (442)  NULL,
    [C2P]            NVARCHAR (442)  NULL,
    [C2Q]            NVARCHAR (442)  NULL,
    [C2R]            NVARCHAR (442)  NULL,
    [C2S]            NVARCHAR (442)  NULL,
    [C2T]            NVARCHAR (442)  NULL,
    [C2U]            NVARCHAR (442)  NULL,
    [C2V]            NVARCHAR (442)  NULL,
    [C30]            NVARCHAR (442)  NULL,
    [C31]            NVARCHAR (442)  NULL,
    [C32]            NVARCHAR (442)  NULL,
    [C33]            NVARCHAR (442)  NULL,
    [C34]            NVARCHAR (442)  NULL,
    [C35]            NVARCHAR (442)  NULL,
    [C36]            NVARCHAR (442)  NULL,
    [DisplayName_L8] NVARCHAR (442)  NULL,
    [I4O]            BIGINT          NULL,
    [C37]            NVARCHAR (442)  NULL,
    [C38]            NVARCHAR (442)  NULL,
    [C39]            NVARCHAR (442)  NULL,
    [C3A]            NVARCHAR (442)  NULL,
    [C3B]            NVARCHAR (442)  NULL,
    [C3C]            NVARCHAR (442)  NULL,
    [C3D]            NVARCHAR (442)  NULL,
    [C3E]            NVARCHAR (442)  NULL,
    [C3F]            NVARCHAR (442)  NULL,
    [C3G]            NVARCHAR (442)  NULL,
    [C3H]            NVARCHAR (442)  NULL,
    [C3I]            NVARCHAR (442)  NULL,
    [C3J]            NVARCHAR (442)  NULL,
    [C3K]            NVARCHAR (442)  NULL,
    [C3L]            NVARCHAR (442)  NULL,
    [C3M]            NVARCHAR (442)  NULL,
    [C3N]            NVARCHAR (442)  NULL,
    [C3O]            NVARCHAR (442)  NULL,
    [C3P]            NVARCHAR (442)  NULL,
    [C3Q]            NVARCHAR (442)  NULL,
    [C3R]            NVARCHAR (442)  NULL,
    [C3S]            NVARCHAR (442)  NULL,
    [C3T]            NVARCHAR (442)  NULL,
    [C3U]            NVARCHAR (442)  NULL,
    [C3V]            NVARCHAR (442)  NULL,
);

/* Apply partitioning if possible.*/
IF EXISTS (select 1 from sys.partition_schemes WHERE name='HistoryScheme')
BEGIN
ALTER TABLE [dbo].[tmp_ms_xx_UR_Resources] ADD CONSTRAINT "tmp_ms_xx_constraint_PK_Resources1" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
CREATE UNIQUE CLUSTERED INDEX "tmp_ms_xx_index_IX_Resources1" ON "tmp_ms_xx_UR_Resources"("ValidTo" ASC, "Type" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;
ELSE
BEGIN
ALTER TABLE [dbo].[tmp_ms_xx_UR_Resources] ADD CONSTRAINT [tmp_ms_xx_constraint_PK_Resources1] PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC);
CREATE UNIQUE CLUSTERED INDEX [tmp_ms_xx_index_IX_Resources1]
    ON [dbo].[tmp_ms_xx_UR_Resources]([ValidTo] ASC, [Type] ASC, [Id] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON);
END;


IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UR_Resources])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_UR_Resources] ([ValidTo], [Type], [Id], [ValidFrom], [Dirty], [DisplayName_L1], [C0], [C1], [C2], [C3], [C4], [C5], [C6], [C7], [C8], [C9], [CA], [CB], [CC], [CD], [CE], [DisplayName_L2], [I40], [I41], [I42], [I43], [I44], [CF], [CG], [CH], [CI], [CJ], [CK], [CL], [CM], [CN], [CO], [CP], [CQ], [CR], [CS], [CT], [DisplayName_L3], [I45], [I46], [I47], [I48], [I49], [CU], [CV], [C10], [C11], [C12], [C13], [C14], [C15], [C16], [C17], [C18], [C19], [C1A], [C1B], [C1C], [DisplayName_L4], [I4A], [I4B], [I4C], [I4D], [I4E], [C1D], [C1E], [C1F], [C1G], [C1H], [C1I], [C1J], [C1K], [C1L], [C1M], [C1N], [C1O], [C1P], [C1Q], [C1R], [DisplayName_L5], [I4F], [I4G], [I4H], [I4I], [C1S], [C1T], [C1U], [C1V], [C20], [C21], [C22], [C23], [C24], [C25], [C26], [C27], [C28], [C29], [C2A], [DisplayName_L6], [I4J], [I4K], [I4L], [C2B], [C2C], [C2D], [C2E], [C2F], [C2G], [C2H], [C2I], [C2J], [C2K], [C2L], [C2M], [C2N], [DisplayName_L7], [I4M], [I4N], [C2O], [C2P], [C2Q], [C2R], [C2S], [C2T], [C2U], [C2V], [C30], [C31], [C32], [C33], [C34], [C35], [C36], [DisplayName_L8], [I4O], [C37], [C38], [C39], [C3A], [C3B], [C3C], [C3D], [C3E], [C3F], [C3G], [C3H], [C3I], [C3J], [C3K], [C3L], [C3M], [C3N], [C3O], [C3P], [C3Q], [C3R], [C3S], [C3T], [C3U], [C3V])
        SELECT   [ValidTo],
                 [Type],
                 [Id],
                 [ValidFrom],
                 [Dirty],
                 [DisplayName_L1],
                 [C0],
                 [C1],
                 [C2],
                 [C3],
                 [C4],
                 [C5],
                 [C6],
                 [C7],
                 [C8],
                 [C9],
                 [CA],
                 [CB],
                 [CC],
                 [CD],
                 [CE],
                 [DisplayName_L2],
                 [I40],
                 [I41],
                 [I42],
                 [I43],
                 [I44],
                 [CF],
                 [CG],
                 [CH],
                 [CI],
                 [CJ],
                 [CK],
                 [CL],
                 [CM],
                 [CN],
                 [CO],
                 [CP],
                 [CQ],
                 [CR],
                 [CS],
                 [CT],
                 [DisplayName_L3],
                 [I45],
                 [I46],
                 [I47],
                 [I48],
                 [I49],
                 [CU],
                 [CV],
                 [C10],
                 [C11],
                 [C12],
                 [C13],
                 [C14],
                 [C15],
                 [C16],
                 [C17],
                 [C18],
                 [C19],
                 [C1A],
                 [C1B],
                 [C1C],
                 [DisplayName_L4],
                 [I4A],
                 [I4B],
                 [I4C],
                 [I4D],
                 [I4E],
                 [C1D],
                 [C1E],
                 [C1F],
                 [C1G],
                 [C1H],
                 [C1I],
                 [C1J],
                 [C1K],
                 [C1L],
                 [C1M],
                 [C1N],
                 [C1O],
                 [C1P],
                 [C1Q],
                 [C1R],
                 [DisplayName_L5],
                 [I4F],
                 [I4G],
                 [I4H],
                 [I4I],
                 [C1S],
                 [C1T],
                 [C1U],
                 [C1V],
                 [C20],
                 [C21],
                 [C22],
                 [C23],
                 [C24],
                 [C25],
                 [C26],
                 [C27],
                 [C28],
                 [C29],
                 [C2A],
                 [DisplayName_L6],
                 [I4J],
                 [I4K],
                 [I4L],
                 [C2B],
                 [C2C],
                 [C2D],
                 [C2E],
                 [C2F],
                 [C2G],
                 [C2H],
                 [C2I],
                 [C2J],
                 [C2K],
                 [C2L],
                 [C2M],
                 [C2N],
                 [DisplayName_L7],
                 [I4M],
                 [I4N],
                 [C2O],
                 [C2P],
                 [C2Q],
                 [C2R],
                 [C2S],
                 [C2T],
                 [C2U],
                 [C2V],
                 [C30],
                 [C31],
                 [C32],
                 [C33],
                 [C34],
                 [C35],
                 [C36],
                 [DisplayName_L8],
                 [I4O],
                 [C37],
                 [C38],
                 [C39],
                 [C3A],
                 [C3B],
                 [C3C],
                 [C3D],
                 [C3E],
                 [C3F],
                 [C3G],
                 [C3H],
                 [C3I],
                 [C3J],
                 [C3K],
                 [C3L],
                 [C3M],
                 [C3N],
                 [C3O],
                 [C3P],
                 [C3Q],
                 [C3R],
                 [C3S],
                 [C3T],
                 [C3U],
                 [C3V]
        FROM     [dbo].[UR_Resources]
        ORDER BY [ValidTo] ASC, [Type] ASC, [Id] ASC;
    END

DROP TABLE [dbo].[UR_Resources];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UR_Resources]', N'UR_Resources';

EXECUTE sp_rename N'[dbo].[UR_Resources].[tmp_ms_xx_index_IX_Resources1]', N'IX_Resources', N'INDEX';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Resources1]', N'PK_Resources', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_DisplayName_L1]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_DisplayName_L1]
    ON [dbo].[UR_Resources]([DisplayName_L1] ASC, [Id] ASC) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_Dirty]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_Dirty]
    ON [dbo].[UR_Resources]([Dirty] ASC) WHERE "Dirty"=1 AND "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_PrimaryKey]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_PrimaryKey]
    ON [dbo].[UR_Resources]([Type] ASC, [PrimaryKey] ASC, [Id] ASC) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) AND "PrimaryKey" IS NOT NULL WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_U0]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_U0]
    ON [dbo].[UR_Resources]([Type] ASC, [U0] ASC, [Id] ASC) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) AND "U0" IS NOT NULL WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_U1]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_U1]
    ON [dbo].[UR_Resources]([Type] ASC, [U1] ASC, [Id] ASC) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) AND "U1" IS NOT NULL WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_U2]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_U2]
    ON [dbo].[UR_Resources]([Type] ASC, [U2] ASC, [Id] ASC) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) AND "U2" IS NOT NULL WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Creating [dbo].[UR_Resources].[IX_Resources_R0]...';


GO
CREATE NONCLUSTERED INDEX [IX_Resources_R0]
    ON [dbo].[UR_Resources]([Type] ASC, [R0] ASC, [Id] ASC) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121) AND "R0" IS NOT NULL WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
PRINT N'Starting rebuilding table [dbo].[UT_Resources]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UT_Resources] (
    [Id]             BIGINT          NOT NULL,
    [Type]           BIGINT          NOT NULL,
    [DisplayName_L1] NVARCHAR (442)  NULL,
    [PrimaryKey]     NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U0]             NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U1]             NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [U2]             NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL,
    [C0]             NVARCHAR (4000) NULL,
    [C1]             NVARCHAR (4000) NULL,
    [C2]             NVARCHAR (4000) NULL,
    [C3]             NVARCHAR (4000) NULL,
    [C4]             NVARCHAR (442)  NULL,
    [C5]             NVARCHAR (442)  NULL,
    [C6]             NVARCHAR (442)  NULL,
    [C7]             NVARCHAR (442)  NULL,
    [C8]             NVARCHAR (442)  NULL,
    [C9]             NVARCHAR (442)  NULL,
    [CA]             NVARCHAR (442)  NULL,
    [CB]             NVARCHAR (442)  NULL,
    [CC]             NVARCHAR (442)  NULL,
    [CD]             NVARCHAR (442)  NULL,
    [CE]             NVARCHAR (442)  NULL,
    [DisplayName_L2] NVARCHAR (442)  NULL,
    [I40]            BIGINT          NULL,
    [I41]            BIGINT          NULL,
    [I42]            BIGINT          NULL,
    [I43]            BIGINT          NULL,
    [I44]            BIGINT          NULL,
    [CF]             NVARCHAR (442)  NULL,
    [CG]             NVARCHAR (442)  NULL,
    [CH]             NVARCHAR (442)  NULL,
    [CI]             NVARCHAR (442)  NULL,
    [CJ]             NVARCHAR (442)  NULL,
    [CK]             NVARCHAR (442)  NULL,
    [CL]             NVARCHAR (442)  NULL,
    [CM]             NVARCHAR (442)  NULL,
    [CN]             NVARCHAR (442)  NULL,
    [CO]             NVARCHAR (442)  NULL,
    [CP]             NVARCHAR (442)  NULL,
    [CQ]             NVARCHAR (442)  NULL,
    [CR]             NVARCHAR (442)  NULL,
    [CS]             NVARCHAR (442)  NULL,
    [CT]             NVARCHAR (442)  NULL,
    [DisplayName_L3] NVARCHAR (442)  NULL,
    [I45]            BIGINT          NULL,
    [I46]            BIGINT          NULL,
    [I47]            BIGINT          NULL,
    [I48]            BIGINT          NULL,
    [I49]            BIGINT          NULL,
    [CU]             NVARCHAR (442)  NULL,
    [CV]             NVARCHAR (442)  NULL,
    [C10]            NVARCHAR (442)  NULL,
    [C11]            NVARCHAR (442)  NULL,
    [C12]            NVARCHAR (442)  NULL,
    [C13]            NVARCHAR (442)  NULL,
    [C14]            NVARCHAR (442)  NULL,
    [C15]            NVARCHAR (442)  NULL,
    [C16]            NVARCHAR (442)  NULL,
    [C17]            NVARCHAR (442)  NULL,
    [C18]            NVARCHAR (442)  NULL,
    [C19]            NVARCHAR (442)  NULL,
    [C1A]            NVARCHAR (442)  NULL,
    [C1B]            NVARCHAR (442)  NULL,
    [C1C]            NVARCHAR (442)  NULL,
    [DisplayName_L4] NVARCHAR (442)  NULL,
    [I4A]            BIGINT          NULL,
    [I4B]            BIGINT          NULL,
    [I4C]            BIGINT          NULL,
    [I4D]            BIGINT          NULL,
    [I4E]            BIGINT          NULL,
    [C1D]            NVARCHAR (442)  NULL,
    [C1E]            NVARCHAR (442)  NULL,
    [C1F]            NVARCHAR (442)  NULL,
    [C1G]            NVARCHAR (442)  NULL,
    [C1H]            NVARCHAR (442)  NULL,
    [C1I]            NVARCHAR (442)  NULL,
    [C1J]            NVARCHAR (442)  NULL,
    [C1K]            NVARCHAR (442)  NULL,
    [C1L]            NVARCHAR (442)  NULL,
    [C1M]            NVARCHAR (442)  NULL,
    [C1N]            NVARCHAR (442)  NULL,
    [C1O]            NVARCHAR (442)  NULL,
    [C1P]            NVARCHAR (442)  NULL,
    [C1Q]            NVARCHAR (442)  NULL,
    [C1R]            NVARCHAR (442)  NULL,
    [DisplayName_L5] NVARCHAR (442)  NULL,
    [I4F]            BIGINT          NULL,
    [I4G]            BIGINT          NULL,
    [I4H]            BIGINT          NULL,
    [I4I]            BIGINT          NULL,
    [C1S]            NVARCHAR (442)  NULL,
    [C1T]            NVARCHAR (442)  NULL,
    [C1U]            NVARCHAR (442)  NULL,
    [C1V]            NVARCHAR (442)  NULL,
    [C20]            NVARCHAR (442)  NULL,
    [C21]            NVARCHAR (442)  NULL,
    [C22]            NVARCHAR (442)  NULL,
    [C23]            NVARCHAR (442)  NULL,
    [C24]            NVARCHAR (442)  NULL,
    [C25]            NVARCHAR (442)  NULL,
    [C26]            NVARCHAR (442)  NULL,
    [C27]            NVARCHAR (442)  NULL,
    [C28]            NVARCHAR (442)  NULL,
    [C29]            NVARCHAR (442)  NULL,
    [C2A]            NVARCHAR (442)  NULL,
    [DisplayName_L6] NVARCHAR (442)  NULL,
    [I4J]            BIGINT          NULL,
    [I4K]            BIGINT          NULL,
    [I4L]            BIGINT          NULL,
    [C2B]            NVARCHAR (442)  NULL,
    [C2C]            NVARCHAR (442)  NULL,
    [C2D]            NVARCHAR (442)  NULL,
    [C2E]            NVARCHAR (442)  NULL,
    [C2F]            NVARCHAR (442)  NULL,
    [C2G]            NVARCHAR (442)  NULL,
    [C2H]            NVARCHAR (442)  NULL,
    [C2I]            NVARCHAR (442)  NULL,
    [C2J]            NVARCHAR (442)  NULL,
    [C2K]            NVARCHAR (442)  NULL,
    [C2L]            NVARCHAR (442)  NULL,
    [C2M]            NVARCHAR (442)  NULL,
    [C2N]            NVARCHAR (442)  NULL,
    [DisplayName_L7] NVARCHAR (442)  NULL,
    [I4M]            BIGINT          NULL,
    [I4N]            BIGINT          NULL,
    [C2O]            NVARCHAR (442)  NULL,
    [C2P]            NVARCHAR (442)  NULL,
    [C2Q]            NVARCHAR (442)  NULL,
    [C2R]            NVARCHAR (442)  NULL,
    [C2S]            NVARCHAR (442)  NULL,
    [C2T]            NVARCHAR (442)  NULL,
    [C2U]            NVARCHAR (442)  NULL,
    [C2V]            NVARCHAR (442)  NULL,
    [C30]            NVARCHAR (442)  NULL,
    [C31]            NVARCHAR (442)  NULL,
    [C32]            NVARCHAR (442)  NULL,
    [C33]            NVARCHAR (442)  NULL,
    [C34]            NVARCHAR (442)  NULL,
    [C35]            NVARCHAR (442)  NULL,
    [C36]            NVARCHAR (442)  NULL,
    [DisplayName_L8] NVARCHAR (442)  NULL,
    [I4O]            BIGINT          NULL,
    [C37]            NVARCHAR (442)  NULL,
    [C38]            NVARCHAR (442)  NULL,
    [C39]            NVARCHAR (442)  NULL,
    [C3A]            NVARCHAR (442)  NULL,
    [C3B]            NVARCHAR (442)  NULL,
    [C3C]            NVARCHAR (442)  NULL,
    [C3D]            NVARCHAR (442)  NULL,
    [C3E]            NVARCHAR (442)  NULL,
    [C3F]            NVARCHAR (442)  NULL,
    [C3G]            NVARCHAR (442)  NULL,
    [C3H]            NVARCHAR (442)  NULL,
    [C3I]            NVARCHAR (442)  NULL,
    [C3J]            NVARCHAR (442)  NULL,
    [C3K]            NVARCHAR (442)  NULL,
    [C3L]            NVARCHAR (442)  NULL,
    [C3M]            NVARCHAR (442)  NULL,
    [C3N]            NVARCHAR (442)  NULL,
    [C3O]            NVARCHAR (442)  NULL,
    [C3P]            NVARCHAR (442)  NULL,
    [C3Q]            NVARCHAR (442)  NULL,
    [C3R]            NVARCHAR (442)  NULL,
    [C3S]            NVARCHAR (442)  NULL,
    [C3T]            NVARCHAR (442)  NULL,
    [C3U]            NVARCHAR (442)  NULL,
    [C3V]            NVARCHAR (442)  NULL
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UT_Resources])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_UT_Resources] ([Id], [Type], [DisplayName_L1], [C0], [C1], [C2], [C3], [C4], [C5], [C6], [C7], [C8], [C9], [CA], [CB], [CC], [CD], [CE], [DisplayName_L2], [I40], [I41], [I42], [I43], [I44], [CF], [CG], [CH], [CI], [CJ], [CK], [CL], [CM], [CN], [CO], [CP], [CQ], [CR], [CS], [CT], [DisplayName_L3], [I45], [I46], [I47], [I48], [I49], [CU], [CV], [C10], [C11], [C12], [C13], [C14], [C15], [C16], [C17], [C18], [C19], [C1A], [C1B], [C1C], [DisplayName_L4], [I4A], [I4B], [I4C], [I4D], [I4E], [C1D], [C1E], [C1F], [C1G], [C1H], [C1I], [C1J], [C1K], [C1L], [C1M], [C1N], [C1O], [C1P], [C1Q], [C1R], [DisplayName_L5], [I4F], [I4G], [I4H], [I4I], [C1S], [C1T], [C1U], [C1V], [C20], [C21], [C22], [C23], [C24], [C25], [C26], [C27], [C28], [C29], [C2A], [DisplayName_L6], [I4J], [I4K], [I4L], [C2B], [C2C], [C2D], [C2E], [C2F], [C2G], [C2H], [C2I], [C2J], [C2K], [C2L], [C2M], [C2N], [DisplayName_L7], [I4M], [I4N], [C2O], [C2P], [C2Q], [C2R], [C2S], [C2T], [C2U], [C2V], [C30], [C31], [C32], [C33], [C34], [C35], [C36], [DisplayName_L8], [I4O], [C37], [C38], [C39], [C3A], [C3B], [C3C], [C3D], [C3E], [C3F], [C3G], [C3H], [C3I], [C3J], [C3K], [C3L], [C3M], [C3N], [C3O], [C3P], [C3Q], [C3R], [C3S], [C3T], [C3U], [C3V])
        SELECT [Id],
               [Type],
               [DisplayName_L1],
               [C0],
               [C1],
               [C2],
               [C3],
               [C4],
               [C5],
               [C6],
               [C7],
               [C8],
               [C9],
               [CA],
               [CB],
               [CC],
               [CD],
               [CE],
               [DisplayName_L2],
               [I40],
               [I41],
               [I42],
               [I43],
               [I44],
               [CF],
               [CG],
               [CH],
               [CI],
               [CJ],
               [CK],
               [CL],
               [CM],
               [CN],
               [CO],
               [CP],
               [CQ],
               [CR],
               [CS],
               [CT],
               [DisplayName_L3],
               [I45],
               [I46],
               [I47],
               [I48],
               [I49],
               [CU],
               [CV],
               [C10],
               [C11],
               [C12],
               [C13],
               [C14],
               [C15],
               [C16],
               [C17],
               [C18],
               [C19],
               [C1A],
               [C1B],
               [C1C],
               [DisplayName_L4],
               [I4A],
               [I4B],
               [I4C],
               [I4D],
               [I4E],
               [C1D],
               [C1E],
               [C1F],
               [C1G],
               [C1H],
               [C1I],
               [C1J],
               [C1K],
               [C1L],
               [C1M],
               [C1N],
               [C1O],
               [C1P],
               [C1Q],
               [C1R],
               [DisplayName_L5],
               [I4F],
               [I4G],
               [I4H],
               [I4I],
               [C1S],
               [C1T],
               [C1U],
               [C1V],
               [C20],
               [C21],
               [C22],
               [C23],
               [C24],
               [C25],
               [C26],
               [C27],
               [C28],
               [C29],
               [C2A],
               [DisplayName_L6],
               [I4J],
               [I4K],
               [I4L],
               [C2B],
               [C2C],
               [C2D],
               [C2E],
               [C2F],
               [C2G],
               [C2H],
               [C2I],
               [C2J],
               [C2K],
               [C2L],
               [C2M],
               [C2N],
               [DisplayName_L7],
               [I4M],
               [I4N],
               [C2O],
               [C2P],
               [C2Q],
               [C2R],
               [C2S],
               [C2T],
               [C2U],
               [C2V],
               [C30],
               [C31],
               [C32],
               [C33],
               [C34],
               [C35],
               [C36],
               [DisplayName_L8],
               [I4O],
               [C37],
               [C38],
               [C39],
               [C3A],
               [C3B],
               [C3C],
               [C3D],
               [C3E],
               [C3F],
               [C3G],
               [C3H],
               [C3I],
               [C3J],
               [C3K],
               [C3L],
               [C3M],
               [C3N],
               [C3O],
               [C3P],
               [C3Q],
               [C3R],
               [C3S],
               [C3T],
               [C3U],
               [C3V]
        FROM   [dbo].[UT_Resources];
    END

DROP TABLE [dbo].[UT_Resources];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UT_Resources]', N'UT_Resources';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[UT_BinNvarChar]...';


GO
CREATE TABLE [dbo].[UT_BinNvarChar] (
    [Id]         BIGINT          NOT NULL,
    [PrimaryKey] NVARCHAR (4000) COLLATE Latin1_General_BIN2 NOT NULL,
    [Value]      NVARCHAR (4000) COLLATE Latin1_General_BIN2 NULL
);


GO
PRINT N'Creating [dbo].[UT_ResourceNvarChar]...';


GO
CREATE TABLE [dbo].[UT_ResourceNvarChar] (
    [Id]         BIGINT          NOT NULL,
    [PrimaryKey] NVARCHAR (4000) COLLATE Latin1_General_BIN2 NOT NULL,
    [Value]      NVARCHAR (4000) NULL
);


GO
PRINT N'Creating [dbo].[UR_Resources].[S_Resources_Type]...';


GO
CREATE STATISTICS [S_Resources_Type]
    ON [dbo].[UR_Resources]([Type]) WHERE "ValidTo"=CONVERT(DATETIME2(2),'9999-12-31 23:59:59.999',121)
    WITH FULLSCAN;


GO
PRINT N'Creating [dbo].[FK_ResourceChanges_Type]...';


GO
ALTER TABLE [dbo].[UR_ResourceChanges] WITH NOCHECK
    ADD CONSTRAINT [FK_ResourceChanges_Type] FOREIGN KEY ([Type]) REFERENCES [dbo].[UM_EntityTypes] ([Id]);


GO
ALTER TABLE [dbo].[UR_ResourceChanges] NOCHECK CONSTRAINT [FK_ResourceChanges_Type];


GO
PRINT N'Creating [dbo].[FK_Resources_Type]...';


GO
ALTER TABLE [dbo].[UR_Resources] WITH NOCHECK
    ADD CONSTRAINT [FK_Resources_Type] FOREIGN KEY ([Type]) REFERENCES [dbo].[UM_EntityTypes] ([Id]);


GO
ALTER TABLE [dbo].[UR_Resources] NOCHECK CONSTRAINT [FK_Resources_Type];

/* Recreate index with partitioning if needed */
GO
IF CAST(SERVERPROPERTY('Edition') AS varchar(30)) LIKE 'SQL Azure%'
    OR CAST(SERVERPROPERTY('Edition') AS varchar(30)) LIKE 'Enterprise%'
    OR CAST(SERVERPROPERTY('Edition') AS varchar(30)) LIKE 'Developer%'
    OR CAST(PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS varchar(30)), 4) AS int) > 13 --SQL 2017 and later
    OR (CAST(PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS varchar(30)), 4) AS int) = 13 --SQL 2016
    AND CAST(PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS varchar(30)), 2) AS int) >= 4001) --SP1 or greater
BEGIN
IF NOT EXISTS(select 1 from sys.partition_schemes WHERE name='HistoryScheme')
BEGIN
EXEC sp_executesql N'CREATE PARTITION FUNCTION "HistoryFunction"(DateTime2(2)) AS RANGE RIGHT FOR VALUES (CONVERT(DATETIME2(2),''9999-12-31 23:59:59.999'',121));
CREATE PARTITION SCHEME "HistoryScheme" AS PARTITION "HistoryFunction" TO ("PRIMARY", "PRIMARY");';
END;
--- Start UR_Resources ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='IX_Resources'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='HistoryScheme'
where p.object_id =OBJECT_ID('ur_resources'))
BEGIN
DROP INDEX "IX_Resources" ON "UR_Resources";
CREATE UNIQUE CLUSTERED INDEX "IX_Resources" ON "UR_Resources"("ValidTo" ASC, "Type" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='pk_resources'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('ur_resources'))
BEGIN
ALTER TABLE "UR_Resources" DROP CONSTRAINT "PK_Resources";
ALTER TABLE "UR_Resources" ADD CONSTRAINT "PK_Resources" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- Start UR_ResourceLinks ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='IX_ResourceLinks_1'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UR_ResourceLinks'))
BEGIN
DROP INDEX "IX_ResourceLinks_1" ON "UR_ResourceLinks";
CREATE UNIQUE CLUSTERED INDEX "IX_ResourceLinks_1" ON "UR_ResourceLinks"("ValidTo" ASC, "Type" ASC, "R1_Id" ASC, "R2_Id" ASC, "ValidFrom" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='IX_ResourceLinks_2'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UR_ResourceLinks'))
BEGIN
DROP INDEX "IX_ResourceLinks_2" ON "UR_ResourceLinks";
CREATE UNIQUE NONCLUSTERED INDEX "IX_ResourceLinks_2" ON "UR_ResourceLinks"("ValidTo" ASC, "Type" ASC, "R2_Id" ASC, "R1_Id" ASC, "ValidFrom" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;

--- Start UR_ResourceFiles ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='IX_ResourceFiles'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UR_ResourceFiles'))
BEGIN
DROP INDEX "IX_ResourceFiles" ON "UR_ResourceFiles";
CREATE CLUSTERED INDEX "IX_ResourceFiles"
    ON "UR_ResourceFiles"("ValidTo" ASC, "Property_Id" ASC, "Resource_Id" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

    

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='IX_ResourceFiles2'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UR_ResourceFiles'))
BEGIN
DROP INDEX "IX_ResourceFiles2" ON "UR_ResourceFiles";
CREATE INDEX "IX_ResourceFiles2"
    ON "UR_ResourceFiles"("Property_Id" ASC,"Resource_Id" ASC, "ValidFrom" DESC)
	INCLUDE (Id, "validto","mimetype","filename") ON "HistoryScheme"("ValidTo");
END;




IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_ResourceFiles'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UR_ResourceFiles'))
BEGIN
ALTER TABLE "UR_ResourceFiles" DROP CONSTRAINT "PK_ResourceFiles";
ALTER TABLE "UR_ResourceFiles" ADD CONSTRAINT "PK_ResourceFiles" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- UP AssignedCompositeRoles---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_AssignedCompositeRoles'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedCompositeRoles'))
BEGIN
ALTER TABLE "UP_AssignedCompositeRoles" DROP CONSTRAINT "PK_AssignedCompositeRoles";
ALTER TABLE "UP_AssignedCompositeRoles" ADD CONSTRAINT "PK_AssignedCompositeRoles" PRIMARY KEY CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "Role_Id" ASC, "ParametersContext_Id" ASC, "StartDate" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='UK_AssignedCompositeRoles'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedCompositeRoles'))
BEGIN
ALTER TABLE "UP_AssignedCompositeRoles" DROP CONSTRAINT "UK_AssignedCompositeRoles";
ALTER TABLE "UP_AssignedCompositeRoles" ADD CONSTRAINT "UK_AssignedCompositeRoles" UNIQUE ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- UP AssignedSingleRoles---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_AssignedSingleRoles'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedSingleRoles'))
BEGIN
ALTER TABLE "UP_AssignedSingleRoles" DROP CONSTRAINT "PK_AssignedSingleRoles";
ALTER TABLE "UP_AssignedSingleRoles" ADD CONSTRAINT "PK_AssignedSingleRoles" PRIMARY KEY CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "Role_Id" ASC, "ParametersContext_Id" ASC, "StartDate" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='UK_AssignedSingleRoles'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedSingleRoles'))
BEGIN
ALTER TABLE "UP_AssignedSingleRoles" DROP CONSTRAINT "UK_AssignedSingleRoles";
ALTER TABLE "UP_AssignedSingleRoles" ADD CONSTRAINT "UK_AssignedSingleRoles" UNIQUE ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- UP AssignedResourceTypes ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_AssignedResourceTypes'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceTypes'))
BEGIN
ALTER TABLE "UP_AssignedResourceTypes" DROP CONSTRAINT "PK_AssignedResourceTypes"; 
ALTER TABLE "UP_AssignedResourceTypes" ADD CONSTRAINT "PK_AssignedResourceTypes" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='CK_AssignedResourceTypes'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceTypes'))
BEGIN
ALTER TABLE "UP_AssignedResourceTypes" DROP CONSTRAINT "CK_AssignedResourceTypes"; 
ALTER TABLE "UP_AssignedResourceTypes" ADD CONSTRAINT "CK_AssignedResourceTypes" UNIQUE CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;

--- UP AssignedResourceScalars ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='CK_AssignedResourceScalar'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceScalars'))
BEGIN
ALTER TABLE "UP_AssignedResourceScalars" DROP CONSTRAINT "CK_AssignedResourceScalar" ;
ALTER TABLE "UP_AssignedResourceScalars" ADD CONSTRAINT "CK_AssignedResourceScalar" UNIQUE CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "AssignedResourceType_Id" ASC, "Property_Id" ASC, "StartDate" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_AssignedResourceScalar'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceScalars'))
BEGIN
ALTER TABLE "UP_AssignedResourceScalars" DROP CONSTRAINT "PK_AssignedResourceScalar";
ALTER TABLE "UP_AssignedResourceScalars" ADD CONSTRAINT "PK_AssignedResourceScalar" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- UP AssignedResourceNavigations ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='CK_AssignedResourceNavigations'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceNavigations'))
BEGIN
ALTER TABLE "UP_AssignedResourceNavigations" DROP CONSTRAINT "CK_AssignedResourceNavigations";
ALTER TABLE "UP_AssignedResourceNavigations" ADD CONSTRAINT "CK_AssignedResourceNavigations" UNIQUE CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "AssignedResourceType_Id" ASC, "Property_Id" ASC, "Resource_Id" ASC, "StartDate" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON)  ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_AssignedResourceNavigations'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceNavigations'))
BEGIN
ALTER TABLE "UP_AssignedResourceNavigations" DROP CONSTRAINT "PK_AssignedResourceNavigations";
ALTER TABLE "UP_AssignedResourceNavigations" ADD CONSTRAINT "PK_AssignedResourceNavigations" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC)  ON "HistoryScheme"("ValidTo");
END;

--- UP AssignedResourceBinaries ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='CK_AssignedResourceBinaries'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceBinaries'))
BEGIN
ALTER TABLE "UP_AssignedResourceBinaries" DROP CONSTRAINT "CK_AssignedResourceBinaries";
ALTER TABLE "UP_AssignedResourceBinaries" ADD CONSTRAINT "CK_AssignedResourceBinaries" UNIQUE CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "AssignedResourceType_Id" ASC, "Property_Id" ASC, "ResourceFile_Id" ASC, "StartDate" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON)  ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_AssignedResourceBinaries'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_AssignedResourceBinaries'))
BEGIN
ALTER TABLE "UP_AssignedResourceBinaries" DROP CONSTRAINT "PK_AssignedResourceBinaries";
ALTER TABLE "UP_AssignedResourceBinaries" ADD CONSTRAINT "PK_AssignedResourceBinaries" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- UP IdentifiedRisks ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='CK_IdentifiedRisks'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_IdentifiedRisks'))
BEGIN
ALTER TABLE "UP_IdentifiedRisks" DROP CONSTRAINT "CK_IdentifiedRisks";
ALTER TABLE "UP_IdentifiedRisks" ADD CONSTRAINT "CK_IdentifiedRisks" UNIQUE CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_IdentifiedRisks'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_IdentifiedRisks'))
BEGIN
ALTER TABLE "UP_IdentifiedRisks" DROP CONSTRAINT "PK_IdentifiedRisks";
ALTER TABLE "UP_IdentifiedRisks" ADD CONSTRAINT "PK_IdentifiedRisks" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC,"Id" ASC) ON "HistoryScheme"("ValidTo");
END;

--- UP ResourceRiskScores ---

IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='CK_ResourceRiskScores'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_ResourceRiskScores'))
BEGIN
ALTER TABLE "UP_ResourceRiskScores" DROP CONSTRAINT "CK_ResourceRiskScores";
ALTER TABLE "UP_ResourceRiskScores" ADD CONSTRAINT "CK_ResourceRiskScores" UNIQUE CLUSTERED ("ValidTo" ASC, "OwnerType" ASC, "Owner_Id" ASC, "Id" ASC) WITH (FILLFACTOR=90, PAD_INDEX=ON) ON "HistoryScheme"("ValidTo");
END;



IF NOT EXISTS(select 1 from sys.partitions p
		join sys.indexes i on p.object_id = i.object_id and p.index_id = i.index_id and  i.name='PK_ResourceRiskScores'
		join sys.partition_schemes ps on i.data_space_id = ps.data_space_id and ps.name='historyscheme'
where p.object_id =OBJECT_ID('UP_ResourceRiskScores'))
BEGIN
ALTER TABLE "UP_ResourceRiskScores" DROP CONSTRAINT "PK_ResourceRiskScores";
ALTER TABLE "UP_ResourceRiskScores" ADD CONSTRAINT "PK_ResourceRiskScores" PRIMARY KEY NONCLUSTERED ("ValidTo" ASC, "Id" ASC) ON "HistoryScheme"("ValidTo");
END;

END;


