IF COL_LENGTH('dbo.UM_Settings', 'B2') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B2" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B3') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B3" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B4') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B4" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B5') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B5" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B6') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B6" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B7') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B7" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B8') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B8" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B9') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B9" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B10') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B10" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B11') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B11" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B12') IS NULL
BEGIN
ALTER TABLE "UM_Settings" ADD "B12" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B13') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B13" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B14') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B14" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'B15') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "B15" VARBINARY(MAX) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'C12') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "C12" NVARCHAR(4000) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'C13') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "C13" NVARCHAR(4000) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'C14') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "C14" NVARCHAR(4000) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'C15') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "C15" NVARCHAR(4000) NULL;
END
GO

IF COL_LENGTH('dbo.UM_Settings', 'C16') IS NULL
BEGIN
    ALTER TABLE "UM_Settings" ADD "C16" NVARCHAR(4000) NULL;
END
GO
