IF NOT EXISTS (
    SELECT id FROM uj_jobs WHERE id = 2147483647
)
BEGIN
    INSERT INTO uj_jobs(id, identifier, displayname_l1, userstartdenied, loglevel) VALUES (2147483647, 'DeployProductGeneratedConfiguration', 'Deploy configuration generated by the product', 1, 6);
END

IF NOT EXISTS (
    SELECT id FROM uj_tasks WHERE id = 2147483647
)
BEGIN
    INSERT INTO uj_tasks(id, identifier, displayname_l1, tasktype, inputpath, loglevel) VALUES (2147483647, 'DeployProductGeneratedConfiguration', 'Deploy configuration generated by the product', 41, '../Temp', 6);
END

IF NOT EXISTS (
    SELECT id FROM uj_jobsteps WHERE id = 2147483647
)
BEGIN
    INSERT INTO uj_jobsteps(id, task_id, job_id, launchorder, level) VALUES (2147483647, 2147483647, 2147483647, 0, 0);
END

GO
