BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.AccessCertificationNotify', '@using Usercube.Notifications.AccessCertification.Api')
    WHERE Identifier = 'PendingAccessCertificationModel'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.Notifications.AccessCertification.Impl'+CHAR(10)+'@using Usercube.Notifications.AccessCertification.Api', '@using Usercube.Notifications.AccessCertification.Api')
    WHERE Identifier = 'PendingAccessCertificationModel'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.Notifications.ManualProvisioning.Impl', '@using Usercube.Notifications.ManualProvisioning.Api')
    WHERE Identifier = 'PerformManualProvisioningSummary'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.ProvisioningPolicy.Notifier.Models', '@using Usercube.Notifications.ProvisioningPolicy.Api')
    WHERE Identifier = 'RolePolicySummary'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewProvisioning.Api')
    WHERE Identifier = 'WorkflowReviewProvisioningSummary'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.Application.DeltaProvisioning.Notification', '@using Usercube.Notifications.ReviewRoles.Api')
    WHERE Identifier = 'WorkflowReviewRolesSummary'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.ProvisioningPolicy.GenerateOrders.Impl', '@using Usercube.Notifications.BlockedProvisioning.Api')
    WHERE Identifier = 'BlockedProvisioningInformations'
END

BEGIN
    UPDATE UN_NotificationTemplates
    SET
        BodyTemplate_L1 = REPLACE(BodyTemplate_L1, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L2 = REPLACE(BodyTemplate_L2, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L3 = REPLACE(BodyTemplate_L3, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L4 = REPLACE(BodyTemplate_L4, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L5 = REPLACE(BodyTemplate_L5, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L6 = REPLACE(BodyTemplate_L6, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L7 = REPLACE(BodyTemplate_L7, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L8 = REPLACE(BodyTemplate_L8, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L9 = REPLACE(BodyTemplate_L9, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L10 = REPLACE(BodyTemplate_L10, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L11 = REPLACE(BodyTemplate_L11, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L12 = REPLACE(BodyTemplate_L12, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L13 = REPLACE(BodyTemplate_L13, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L14 = REPLACE(BodyTemplate_L14, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L15 = REPLACE(BodyTemplate_L15, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        BodyTemplate_L16 = REPLACE(BodyTemplate_L16, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L1 = REPLACE(SubjectTemplate_L1, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L2 = REPLACE(SubjectTemplate_L2, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L3 = REPLACE(SubjectTemplate_L3, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L4 = REPLACE(SubjectTemplate_L4, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L5 = REPLACE(SubjectTemplate_L5, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L6 = REPLACE(SubjectTemplate_L6, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L7 = REPLACE(SubjectTemplate_L7, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L8 = REPLACE(SubjectTemplate_L8, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L9 = REPLACE(SubjectTemplate_L9, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L10 = REPLACE(SubjectTemplate_L10, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L11 = REPLACE(SubjectTemplate_L11, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L12 = REPLACE(SubjectTemplate_L12, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L13 = REPLACE(SubjectTemplate_L13, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L14 = REPLACE(SubjectTemplate_L14, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L15 = REPLACE(SubjectTemplate_L15, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api'),
        SubjectTemplate_L16 = REPLACE(SubjectTemplate_L16, '@using Usercube.ProvisioningPolicy.GenerateOrders.Api', '@using Usercube.Notifications.BlockedProvisioning.Api')
    WHERE Identifier = 'BlockedProvisioningInformations'
END

GO
