using System;
using System.Linq;
using Usercube.Expressions.Functions;

[assembly: System.Reflection.AssemblyTitle("Templates")]
[assembly: System.Reflection.AssemblyCompany("Usercube")]
[assembly: System.Reflection.AssemblyProduct("Usercube")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Usercube 2018")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]

#pragma checksum "/Templates" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "d75b5ad3f0fcaa37baa838d289b3488cf339b760"
// <auto-generated/>
#pragma warning disable 1591

namespace Templates
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"d75b5ad3f0fcaa37baa838d289b3488cf339b760", @"/Templates")]
    public class TemplateCCD467C4D2102E0CA7E4F4B16EB454CE1EF61D9C8F46477BA430B06C900DC2B8 : Usercube.Notification.Templating.Entities.RazorTemplateBase<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<table border=""0"" cellpadding=""0"" cellspacing=""0"" class=""body"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;"">
  <tr>
    <td style=""font-family: sans-serif; font-size: 14px; vertical-align: top;"">&nbsp;</td>
    <td class=""container"" style=""font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;"">
      <div class=""content"" style=""box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;"">
        <!-- START CENTERED WHITE CONTAINER -->
        <span class=""preheader"" style=""color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;"">Usercube.</span>
        <table class=""main"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;"">
          <!-- START");
            WriteLiteral(@" MAIN CONTENT AREA -->
          <tr>
            <td class=""wrapper"" style=""font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;"">
              <table border=""0"" cellpadding=""0"" cellspacing=""0"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"">
                <tr>
                  <td style=""font-family: sans-serif; font-size: 14px; vertical-align: top;"">
                    <p style=""font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"">Hello,</p>
                    <span style=""font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"">An update user request needs your attention.</span>
                    <table class=""workflow_summary"" width=""100%"" cellpadding=""0"" cellspacing=""0"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0; padding: 25px 0 0; width: 100%;"">
						<caption st");
            WriteLiteral(@"yle=""display: table-caption; font-weight: 600; text-transform: uppercase; text-align:left"">Summary</caption>
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Date</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 20 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Write(System.DateTime.Now.ToLocalTime().ToString("dd/MM/yyyy hh:mm", System.Globalization.CultureInfo.InvariantCulture));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Full Name</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;""><a");
            BeginWriteAttribute("href", " href=\"", 4057, "\"", 4163, 1);
#nullable restore
#line 21 "/Templates"
WriteAttributeValue("", 4064, new System.Uri(Html.Context.ApplicationUri, $"resources/Directory_User/{ResourceAdapter.GetProperty<long?>(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738368L))}").AbsoluteUri, 4064, 99, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 21 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntity(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738506L)), new Usercube.Data.Api.Entities.PropertyKey(42949673098L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(" ");
#nullable restore
#line 21 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntity(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738506L)), new Usercube.Data.Api.Entities.PropertyKey(42949673102L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</a></span></td></tr>

						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">User Type</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 23 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntity(ResourceAdapter.GetEntity(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738506L)), new Usercube.Data.Api.Entities.PropertyKey(42949673124L)), new Usercube.Data.Api.Entities.PropertyKey(47244640386L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>

						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Contract Start Date</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 25 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Write(ResourceAdapter.GetProperty<System.DateTime?>(ResourceAdapter.GetEntity(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738506L)), new Usercube.Data.Api.Entities.PropertyKey(42949673092L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>
						
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Contract End Date</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 27 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Write(ResourceAdapter.GetProperty<System.DateTime?>(ResourceAdapter.GetEntity(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738506L)), new Usercube.Data.Api.Entities.PropertyKey(42949673090L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>
												
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Department</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 29 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntity(ResourceAdapter.GetEntity(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738506L)), new Usercube.Data.Api.Entities.PropertyKey(42949673108L)), new Usercube.Data.Api.Entities.PropertyKey(8589934723L)));

#line default
#line hidden
#nullable disable
            WriteLiteral("</span></td></tr>\n</table>\n                    ");
#nullable restore
#line 31 "/Templates"
               Write(Html.MessageBody(new { style = "box-sizing: border-box; color: #74787E; font-family: sans-serif, 'Helvetica Neue', Helvetica, sans-serif;" }));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                    
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- END MAIN CONTENT AREA -->
        </table>
        <!-- START FOOTER -->
        <div class=""footer"" style=""clear: both; Margin-top: 10px; text-align: center; width: 100%;"">
          <table border=""0"" cellpadding=""0"" cellspacing=""0"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"">
            <tr>
              <td class=""content-block"" style=""font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;"">
                <span class=""apple-link"" style=""color: #999999; font-size: 12px; text-align: center;"">This message was created by an automated workflow in Usercube. Do not reply.</span>
              </td>
            </tr>            
          </table>
        </div>
        <!-- END FOOTER -->
        <!-- END CENTERED WHITE CONTAINER -->
      ");
            WriteLiteral("</div>\n    </td>\n    <td style=\"font-family: sans-serif; font-size: 14px; vertical-align: top;\">&nbsp;</td>\n  </tr>\n</table>\n");
        }
        public static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> Bindings { get { return bindings; } }
private static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> bindings=new System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding>() { new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(-9223371942365495296L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738506L), new Usercube.Data.Api.Entities.PropertyKey(42949673098L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738506L), new Usercube.Data.Api.Entities.PropertyKey(42949673102L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738506L), new Usercube.Data.Api.Entities.PropertyKey(42949673124L), new Usercube.Data.Api.Entities.PropertyKey(47244640386L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738506L), new Usercube.Data.Api.Entities.PropertyKey(42949673092L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738506L), new Usercube.Data.Api.Entities.PropertyKey(42949673090L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738506L), new Usercube.Data.Api.Entities.PropertyKey(42949673108L), new Usercube.Data.Api.Entities.PropertyKey(8589934723L)) };
    }
}
#pragma warning restore 1591

#pragma checksum "/Templates" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "84ce8071640c132a84bf198d3588d21b1e842ca6"
// <auto-generated/>
#pragma warning disable 1591

namespace Templates
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"84ce8071640c132a84bf198d3588d21b1e842ca6", @"/Templates")]
    public class Template44F2FB1B20A9D036A090E2B7290A99F04599657C6F77B17F6C2D8A1D02C3BC0A : Usercube.Notification.Templating.Entities.RazorTemplateBase<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<table border=""0"" cellpadding=""0"" cellspacing=""0"" class=""body"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;"">
  <tr>
    <td style=""font-family: sans-serif; font-size: 14px; vertical-align: top;"">&nbsp;</td>
    <td class=""container"" style=""font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;"">
      <div class=""content"" style=""box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;"">
        <!-- START CENTERED WHITE CONTAINER -->
        <span class=""preheader"" style=""color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;"">Usercube.</span>
        <table class=""main"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;"">
          <!-- START");
            WriteLiteral(@" MAIN CONTENT AREA -->
          <tr>
            <td class=""wrapper"" style=""font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;"">
              <table border=""0"" cellpadding=""0"" cellspacing=""0"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"">
                <tr>
                  <td style=""font-family: sans-serif; font-size: 14px; vertical-align: top;"">
                    <p style=""font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"">Hello,</p>
                    <span style=""font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"">A new user request needs your attention.</span>
                    <table class=""workflow_summary"" width=""100%"" cellpadding=""0"" cellspacing=""0"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0; padding: 25px 0 0; width: 100%;"">
						<caption style=");
            WriteLiteral(@"""display: table-caption; font-weight: 600; text-transform: uppercase; text-align:left"">Summary</caption>
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Date</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 20 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Write(System.DateTime.Now.ToLocalTime().ToString("dd/MM/yyyy hh:mm", System.Globalization.CultureInfo.InvariantCulture));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Full Name</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;""><a");
            BeginWriteAttribute("href", " href=\"", 4053, "\"", 4159, 1);
#nullable restore
#line 21 "/Templates"
WriteAttributeValue("", 4060, new System.Uri(Html.Context.ApplicationUri, $"resources/Directory_User/{ResourceAdapter.GetProperty<long?>(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738368L))}").AbsoluteUri, 4060, 99, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 21 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntities(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738513L)).First(), new Usercube.Data.Api.Entities.PropertyKey(42949673098L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(" ");
#nullable restore
#line 21 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntities(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738513L)).First(), new Usercube.Data.Api.Entities.PropertyKey(42949673102L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</a></span></td></tr>

						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">User Type</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 23 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntity(ResourceAdapter.GetEntities(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738513L)).First(), new Usercube.Data.Api.Entities.PropertyKey(42949673124L)), new Usercube.Data.Api.Entities.PropertyKey(47244640386L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>

						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Contract Start Date</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 25 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Write(ResourceAdapter.GetProperty<System.DateTime?>(ResourceAdapter.GetEntities(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738513L)).First(), new Usercube.Data.Api.Entities.PropertyKey(42949673092L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>
						
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Contract End Date</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 27 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Write(ResourceAdapter.GetProperty<System.DateTime?>(ResourceAdapter.GetEntities(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738513L)).First(), new Usercube.Data.Api.Entities.PropertyKey(42949673090L)));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span></td></tr>
												
						<tr><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span style=""box-sizing: border-box; color: #9BA2AB; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"" align=""left"">Department</span></td><td class=""workflow_summary_item"" style=""border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding-bottom: 8px;""><span class=""align-right"" style=""box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin: 0;"">");
#nullable restore
#line 29 "/Templates"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write(ResourceAdapter.GetProperty<string?>(ResourceAdapter.GetEntity(ResourceAdapter.GetEntities(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738513L)).First(), new Usercube.Data.Api.Entities.PropertyKey(42949673108L)), new Usercube.Data.Api.Entities.PropertyKey(8589934723L)));

#line default
#line hidden
#nullable disable
            WriteLiteral("</span></td></tr>\n</table>\n                    ");
#nullable restore
#line 31 "/Templates"
               Write(Html.MessageBody(new { style = "box-sizing: border-box; color: #74787E; font-family: sans-serif, 'Helvetica Neue', Helvetica, sans-serif;" }));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                    
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- END MAIN CONTENT AREA -->
        </table>
        <!-- START FOOTER -->
        <div class=""footer"" style=""clear: both; Margin-top: 10px; text-align: center; width: 100%;"">
          <table border=""0"" cellpadding=""0"" cellspacing=""0"" style=""border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"">
            <tr>
              <td class=""content-block"" style=""font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;"">
                <span class=""apple-link"" style=""color: #999999; font-size: 12px; text-align: center;"">This message was created by an automated workflow in Usercube. Do not reply.</span>
              </td>
            </tr>            
          </table>
        </div>
        <!-- END FOOTER -->
        <!-- END CENTERED WHITE CONTAINER -->
      ");
            WriteLiteral("</div>\n    </td>\n    <td style=\"font-family: sans-serif; font-size: 14px; vertical-align: top;\">&nbsp;</td>\n  </tr>\n</table>\n");
        }
        public static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> Bindings { get { return bindings; } }
private static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> bindings=new System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding>() { new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(-9223371942365495296L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738513L), new Usercube.Data.Api.Entities.PropertyKey(42949673098L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738513L), new Usercube.Data.Api.Entities.PropertyKey(42949673102L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738513L), new Usercube.Data.Api.Entities.PropertyKey(42949673124L), new Usercube.Data.Api.Entities.PropertyKey(47244640386L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738513L), new Usercube.Data.Api.Entities.PropertyKey(42949673092L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738513L), new Usercube.Data.Api.Entities.PropertyKey(42949673090L)), new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(34359738513L), new Usercube.Data.Api.Entities.PropertyKey(42949673108L), new Usercube.Data.Api.Entities.PropertyKey(8589934723L)) };
    }
}
#pragma warning restore 1591

#pragma checksum "/Templates" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "b711c6ae4795e6196c4887b7d19fe95f88cf132f"
// <auto-generated/>
#pragma warning disable 1591

namespace Templates
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"b711c6ae4795e6196c4887b7d19fe95f88cf132f", @"/Templates")]
    public class Template8E320995079D38D1C416502DE1121A4530E8C7B1DDCE35285476EACEE5B36806 : Usercube.Notification.Templating.Entities.RazorTemplateBase<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<div>
  <div style=""font-family:'Segoe UI','-apple-system','BlinkMacSystemFont','Roboto','Arial',sans-serif; color:#212121; font-size:14px; background:#f8f8f8"">
    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
      <tbody>
        <tr>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background-color:white; border-bottom:solid #eaeaea 1px"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:20px 24px 25px 24px; background:white"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td>
                            <table border=""0"" cellpadding=""0"" cellspacing=""0"" class=""x_logo"" width=");
            WriteLiteral("\"100%\">\r\n                              <tbody>\r\n                                <tr>\r\n                                  <td valign=\"middle\" style=\"vertical-align:middle\">\r\n                                    <img data-imagetype=\"External\"");
            BeginWriteAttribute("src", " src=\"", 1357, "\"", 1433, 1);
#nullable restore
#line 22 "/Templates"
WriteAttributeValue("", 1363, new System.Uri(Html.Context.ApplicationUri, "logo.png").AbsoluteUri, 1363, 70, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" height=""34"" width=""60"">
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td class=""x_hero"" style=""padding:0px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"" style=""max-width:592px"">
                      <tbody>
                        <tr>
                          <td>
                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                              <tbody>
                                <tr>
                                  <td>
                                    <!-- HEADER START -->
                                    <table>
                                     ");
            WriteLiteral(@" <tbody>
                                        <tr>
                                          <td class=""x_title"" style=""padding:0 0 24px 0; color:#212121; font-size:28px; font-weight:bold; letter-spacing:-0.04em; line-height:40px; word-break:break-word"">
                                            ");
#nullable restore
#line 48 "/Templates"
                                        Write(Html.Context.MessageSubject ?? "Request summary");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                          </td>
                                        </tr>
                                        <tr>
                                          <td class=""x_message"" style=""padding:0 0 24px 0"">
                                            <div>
                                              <p>Bonjour,</p>
                                              <p>Votre demande a bien été prise en compte.</p>
                                            </div>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td style=""padding:0 0 24px 0"">
                                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                                              <tbody>
                                                <tr>
                                                  <td>
                                  ");
            WriteLiteral(@"                  <table border=""0"" cellspacing=""0"" cellpadding=""0"">
                                                      <tbody>
                                                        <tr>
                                                          <td align=""center"" bgcolor=""#007acc"" style=""padding:8px 12px; border-radius:2px"">
                                                            <a");
            BeginWriteAttribute("href", " href=\"", 4236, "\"", 4285, 1);
#nullable restore
#line 69 "/Templates"
WriteAttributeValue("", 4243, Html.Context.ApplicationUri.AbsoluteUri, 4243, 42, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" target=""_blank"" rel=""noopener noreferrer"" data-auth=""NotApplicable"" class=""x_mobile-button x_btn-primary"" style=""font-weight:500; font-size:14px; text-decoration:none; padding:0px; display:inline-block; color:#ffffff"">
                                                              Je me connecte à RHEIA
                                                            </a>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                               ");
            WriteLiteral(@"     </table>
                                    <!-- HEADER END -->
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
        </tr>
        <tr>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background:#f8f8f8"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:24px 24px 8px 24px; max-width:592px"">
                    <table border=""0"" ");
            WriteLiteral(@"width=""100%"" cellpadding=""0"" cellspacing=""0"" class=""x_responsive-table"" style=""vertical-align:middle; background-color:white"">
                      <tbody>
                        <tr>
                          <td style=""padding:16px 24px 24px 24px"">
                            ");
#nullable restore
#line 112 "/Templates"
                       Write(Html.WorkflowSummaryFR(string.Empty, ResourceAdapter.GetProperty<string?>(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738370L))));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style=""padding:24px 24px 24px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td style=""color:#666666; font-size:12px; line-height:18px"">
                            This email is automatically generated by RHEIA. Please do not reply.
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
");
        }
        public static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> Bindings { get { return bindings; } }
private static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> bindings=new System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding>() { new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(-9223371942365495294L)) };
    }
}
#pragma warning restore 1591

#pragma checksum "/Templates" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3e51cc2195a4b00effff80fe0435e4b837860506"
// <auto-generated/>
#pragma warning disable 1591

namespace Templates
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3e51cc2195a4b00effff80fe0435e4b837860506", @"/Templates")]
    public class Template8A6CE8D3568FE47DA968237DCBB289E92364AF554F615EEB3D43A912CA05ACCC : Usercube.Notification.Templating.Entities.RazorTemplateBase<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<div>
  <div style=""font-family:'Segoe UI','-apple-system','BlinkMacSystemFont','Roboto','Arial',sans-serif; color:#212121; font-size:14px; background:#f8f8f8"">
    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
      <tbody>
        <tr>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background-color:white; border-bottom:solid #eaeaea 1px"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:20px 24px 25px 24px; background:white"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td>
                            <table border=""0"" cellpadding=""0"" cellspacing=""0"" class=""x_logo"" width=");
            WriteLiteral("\"100%\">\r\n                              <tbody>\r\n                                <tr>\r\n                                  <td valign=\"middle\" style=\"vertical-align:middle\">\r\n                                    <img data-imagetype=\"External\"");
            BeginWriteAttribute("src", " src=\"", 1357, "\"", 1433, 1);
#nullable restore
#line 22 "/Templates"
WriteAttributeValue("", 1363, new System.Uri(Html.Context.ApplicationUri, "logo.png").AbsoluteUri, 1363, 70, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" height=""34"" width=""60"">
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td class=""x_hero"" style=""padding:0px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"" style=""max-width:592px"">
                      <tbody>
                        <tr>
                          <td>
                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                              <tbody>
                                <tr>
                                  <td>
                                    <!-- HEADER START -->
                                    <table>
                                     ");
            WriteLiteral(@" <tbody>
                                        <tr>
                                          <td class=""x_title"" style=""padding:0 0 24px 0; color:#212121; font-size:28px; font-weight:bold; letter-spacing:-0.04em; line-height:40px; word-break:break-word"">
                                            ");
#nullable restore
#line 48 "/Templates"
                                        Write(Html.Context.MessageSubject ?? "Résumé de la demande");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                          </td>
                                        </tr>
                                        <tr>
                                          <td class=""x_message"" style=""padding:0 0 24px 0"">
                                            <div>
                                              <p>Bonjour,</p>
                                              <p>Vous avez un nouvel élément en attente qui nécessite votre attention.</p>
                                            </div>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td style=""padding:0 0 24px 0"">
                                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                                              <tbody>
                                                <tr>
                                                  <td>
      ");
            WriteLiteral(@"                                              <table border=""0"" cellspacing=""0"" cellpadding=""0"">
                                                      <tbody>
                                                        <tr>
                                                          <td align=""center"" bgcolor=""#007acc"" style=""padding:8px 12px; border-radius:2px"">
                                                            <a");
            BeginWriteAttribute("href", " href=\"", 4269, "\"", 4407, 1);
#nullable restore
#line 69 "/Templates"
WriteAttributeValue("", 4276, new System.Uri(Html.Context.ApplicationUri, $"workflow-management/review/{Html.Context.WorkflowInstanceIdentifier}").AbsoluteUri, 4276, 131, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" target=""_blank"" rel=""noopener noreferrer"" data-auth=""NotApplicable"" class=""x_mobile-button x_btn-primary"" style=""font-weight:500; font-size:14px; text-decoration:none; padding:0px; display:inline-block; color:#ffffff"">
                                                            Consulter la tâche
                                                            </a>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                                    <");
            WriteLiteral(@"/table>
                                    <!-- HEADER END -->
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
        </tr>
        <tr>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background:#f8f8f8"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:24px 24px 8px 24px; max-width:592px"">
                    <table border=""0"" width=");
            WriteLiteral(@"""100%"" cellpadding=""0"" cellspacing=""0"" class=""x_responsive-table"" style=""vertical-align:middle; background-color:white"">
                      <tbody>
                        <tr>
                          <td style=""padding:16px 24px 24px 24px"">
                            ");
#nullable restore
#line 112 "/Templates"
                       Write(Html.WorkflowSummaryFR(string.Empty, ResourceAdapter.GetProperty<string?>(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738370L))));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                            ");
#nullable restore
#line 113 "/Templates"
                       Write(Html.MessageBody(new { style = "box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;" }));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style=""padding:24px 24px 24px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td style=""color:#666666; font-size:12px; line-height:18px"">
                            This email is automatically generated by RHEIA. Please do not reply.
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
");
        }
        public static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> Bindings { get { return bindings; } }
private static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> bindings=new System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding>() { new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(-9223371942365495294L)) };
    }
}
#pragma warning restore 1591

#pragma checksum "/Templates" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f037a81bec34e4018164ef76ca945f5259a889fa"
// <auto-generated/>
#pragma warning disable 1591

namespace Templates
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f037a81bec34e4018164ef76ca945f5259a889fa", @"/Templates")]
    public class Template211ECCEAB5CD67EEE57B22F22A9426814C66DC1DE30D6A0979A018FD59758C0D : Usercube.Notification.Templating.Entities.RazorTemplateBase<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<div>
  <div style=""font-family:'Segoe UI','-apple-system','BlinkMacSystemFont','Roboto','Arial',sans-serif; color:#212121; font-size:14px; background:#f8f8f8"">
    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
      <tbody>
        <tr>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background-color:white; border-bottom:solid #eaeaea 1px"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:20px 24px 25px 24px; background:white"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td>
                            <table border=""0"" cellpadding=""0"" cellspacing=""0"" class=""x_logo"" width=");
            WriteLiteral("\"100%\">\r\n                              <tbody>\r\n                                <tr>\r\n                                  <td valign=\"middle\" style=\"vertical-align:middle\">\r\n                                    <img data-imagetype=\"External\"");
            BeginWriteAttribute("src", " src=\"", 1357, "\"", 1433, 1);
#nullable restore
#line 22 "/Templates"
WriteAttributeValue("", 1363, new System.Uri(Html.Context.ApplicationUri, "logo.png").AbsoluteUri, 1363, 70, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" height=""34"" width=""60"">
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td class=""x_hero"" style=""padding:0px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"" style=""max-width:592px"">
                      <tbody>
                        <tr>
                          <td>
                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                              <tbody>
                                <tr>
                                  <td>
                                    <!-- HEADER START -->
                                    <table>
                                     ");
            WriteLiteral(@" <tbody>
                                        <tr>
                                          <td class=""x_title"" style=""padding:0 0 24px 0; color:#212121; font-size:28px; font-weight:bold; letter-spacing:-0.04em; line-height:40px; word-break:break-word"">
                                            ");
#nullable restore
#line 48 "/Templates"
                                        Write(Html.Context.MessageSubject ?? "Request summary");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                          </td>
                                        </tr>
                                        <tr>
                                          <td class=""x_message"" style=""padding:0 0 24px 0"">
                                            <div>
                                              <p>Bonjour,</p>
                                              <p>Un départ nécessite votre attention. Veuillez consulter les informations de profil de la personne ci-dessous et informer immédiatement votre contact des ressources humaines si quelque chose ne va pas ou manque.</p>
                                            </div>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td style=""padding:0 0 24px 0"">
                                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                              ");
            WriteLiteral(@"                <tbody>
                                                <tr>
                                                  <td>
                                                    <table border=""0"" cellspacing=""0"" cellpadding=""0"">
                                                      <tbody>
                                                        <tr>
                                                          <td align=""center"" bgcolor=""#007acc"" style=""padding:8px 12px; border-radius:2px"">
                                                            <a");
            BeginWriteAttribute("href", " href=\"", 4405, "\"", 4454, 1);
#nullable restore
#line 69 "/Templates"
WriteAttributeValue("", 4412, Html.Context.ApplicationUri.AbsoluteUri, 4412, 42, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" target=""_blank"" rel=""noopener noreferrer"" data-auth=""NotApplicable"" class=""x_mobile-button x_btn-primary"" style=""font-weight:500; font-size:14px; text-decoration:none; padding:0px; display:inline-block; color:#ffffff"">
                                                              Je me connecte à RHEIA
                                                            </a>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                               ");
            WriteLiteral(@"     </table>
                                    <!-- HEADER END -->
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
        </tr>
        <tr>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background:#f8f8f8"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:24px 24px 8px 24px; max-width:592px"">
                    <table border=""0"" ");
            WriteLiteral(@"width=""100%"" cellpadding=""0"" cellspacing=""0"" class=""x_responsive-table"" style=""vertical-align:middle; background-color:white"">
                      <tbody>
                        <tr>
                          <td style=""padding:16px 24px 24px 24px"">
                            ");
#nullable restore
#line 112 "/Templates"
                       Write(Html.WorkflowSummaryFR(string.Empty, ResourceAdapter.GetProperty<string?>(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738370L))));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style=""padding:24px 24px 24px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td style=""color:#666666; font-size:12px; line-height:18px"">
                            This email is automatically generated by RHEIA. Please do not reply.
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
");
        }
        public static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> Bindings { get { return bindings; } }
private static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> bindings=new System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding>() { new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(-9223371942365495294L)) };
    }
}
#pragma warning restore 1591

#pragma checksum "/Templates" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a3939440ca3310730e61e7bac7872af0e424a5c6"
// <auto-generated/>
#pragma warning disable 1591

namespace Templates
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a3939440ca3310730e61e7bac7872af0e424a5c6", @"/Templates")]
    public class Template9833CB5A630546EBBDD61BC618214CA28925F1DF1975C5195E9CCA7140979226 : Usercube.Notification.Templating.Entities.RazorTemplateBase<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<div>
  <div style=""font-family:'Segoe UI','-apple-system','BlinkMacSystemFont','Roboto','Arial',sans-serif; color:#212121; font-size:14px; background:#f8f8f8"">
    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
      <tbody>
        <tr>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background-color:white; border-bottom:solid #eaeaea 1px"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:20px 24px 25px 24px; background:white"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td>
                            <table border=""0"" cellpadding=""0"" cellspacing=""0"" class=""x_logo"" width=");
            WriteLiteral("\"100%\">\r\n                              <tbody>\r\n                                <tr>\r\n                                  <td valign=\"middle\" style=\"vertical-align:middle\">\r\n                                    <img data-imagetype=\"External\"");
            BeginWriteAttribute("src", " src=\"", 1357, "\"", 1433, 1);
#nullable restore
#line 22 "/Templates"
WriteAttributeValue("", 1363, new System.Uri(Html.Context.ApplicationUri, "logo.png").AbsoluteUri, 1363, 70, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" height=""34"" width=""60"">
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td class=""x_hero"" style=""padding:0px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"" style=""max-width:592px"">
                      <tbody>
                        <tr>
                          <td>
                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                              <tbody>
                                <tr>
                                  <td>
                                    <!-- HEADER START -->
                                    <table>
                                     ");
            WriteLiteral(@" <tbody>
                                        <tr>
                                          <td class=""x_title"" style=""padding:0 0 24px 0; color:#212121; font-size:28px; font-weight:bold; letter-spacing:-0.04em; line-height:40px; word-break:break-word"">
                                            ");
#nullable restore
#line 48 "/Templates"
                                        Write(Html.Context.MessageSubject ?? "Request summary");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                          </td>
                                        </tr>
                                        <tr>
                                          <td class=""x_message"" style=""padding:0 0 24px 0"">
                                            <div>
                                              <p>Bonjour,</p>
                                              <p>Une action de mise à jour nécessite votre attention. Veuillez consulter les informations de profil de la personne ci-dessous et informer immédiatement votre contact des ressources humaines si quelque chose ne va pas ou manque.</p>
                                            </div>
                                          </td>
                                        </tr>
                                        <tr>
                                          <td style=""padding:0 0 24px 0"">
                                            <table width=""100%"" border=""0"" cellspacing=""0"" cellpadding=""0"">
              ");
            WriteLiteral(@"                                <tbody>
                                                <tr>
                                                  <td>
                                                    <table border=""0"" cellspacing=""0"" cellpadding=""0"">
                                                      <tbody>
                                                        <tr>
                                                          <td align=""center"" bgcolor=""#007acc"" style=""padding:8px 12px; border-radius:2px"">
                                                            <a");
            BeginWriteAttribute("href", " href=\"", 4421, "\"", 4470, 1);
#nullable restore
#line 69 "/Templates"
WriteAttributeValue("", 4428, Html.Context.ApplicationUri.AbsoluteUri, 4428, 42, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" target=""_blank"" rel=""noopener noreferrer"" data-auth=""NotApplicable"" class=""x_mobile-button x_btn-primary"" style=""font-weight:500; font-size:14px; text-decoration:none; padding:0px; display:inline-block; color:#ffffff"">
                                                              Je me connecte à RHEIA
                                                            </a>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                               ");
            WriteLiteral(@"     </table>
                                    <!-- HEADER END -->
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background-color:white; border-bottom:solid #eaeaea 1px"">
          </td>
        </tr>
        <tr>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
          <td class=""x_content"" width=""640"" style=""padding:0px; max-width:640px; background:#f8f8f8"">
            <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
              <tbody>
                <tr>
                  <td style=""padding:24px 24px 8px 24px; max-width:592px"">
                    <table border=""0"" ");
            WriteLiteral(@"width=""100%"" cellpadding=""0"" cellspacing=""0"" class=""x_responsive-table"" style=""vertical-align:middle; background-color:white"">
                      <tbody>
                        <tr>
                          <td style=""padding:16px 24px 24px 24px"">
                            ");
#nullable restore
#line 112 "/Templates"
                       Write(Html.WorkflowSummaryFR(string.Empty, ResourceAdapter.GetProperty<string?>(Resolver.GetValue<object>("Model"), new Usercube.Data.Api.Entities.PropertyKey(34359738370L))));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style=""padding:24px 24px 24px 24px"">
                    <table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""x_responsive-table"">
                      <tbody>
                        <tr>
                          <td style=""color:#666666; font-size:12px; line-height:18px"">
                            This email is automatically generated by RHEIA. Please do not reply.
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td class=""x_mobile-hide"" style=""background:#f8f8f8""></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
");
        }
        public static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> Bindings { get { return bindings; } }
private static System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding> bindings=new System.Collections.Generic.HashSet<Usercube.Data.Api.Entities.Binding>() { new Usercube.Data.Api.Entities.Binding(new Usercube.Data.Api.Entities.PropertyKey(-9223371942365495294L)) };
    }
}
#pragma warning restore 1591

