IF COL_LENGTH('dbo.UI_FormControls', 'Name') IS NULL
BEGIN
    ALTER TABLE UI_FormControls ADD Name NVARCHAR(442) NULL;
END
GO
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L1') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L1" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L2') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L2" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L3') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L3" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L4') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L4" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L5') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L5" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L6') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L6" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L7') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L7" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L8') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L8" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L9') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L9" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L10') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L10" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L11') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L11" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L12') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L12" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L13') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L13" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L14') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L14" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L15') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L15" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'TableTitle_L16') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "TableTitle_L16" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L1') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L1" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L2') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L2" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L3') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L3" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L4') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L4" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L5') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L5" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L6') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L6" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L7') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L7" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L8') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L8" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L9') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L9" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L10') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L10" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L11') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L11" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L12') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L12" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L13') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L13" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L14') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L14" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L15') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L15" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'AddRowLabel_L16') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "AddRowLabel_L16" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L1') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L1" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L2') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L2" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L3') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L3" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L4') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L4" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L5') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L5" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L6') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L6" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L7') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L7" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L8') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L8" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L9') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L9" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L10') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L10" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L11') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L11" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L12') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L12" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L13') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L13" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L14') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L14" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L15') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L15" NVARCHAR(442) NULL;
END
IF COL_LENGTH('dbo.UI_Forms', 'RemoveRowLabel_L16') IS NULL
BEGIN
    ALTER TABLE UI_Forms ADD "RemoveRowLabel_L16" NVARCHAR(442) NULL;
END
GO
IF COL_LENGTH('dbo.UW_WorkflowInstances', 'IsCompleted') IS NULL
BEGIN
    ALTER TABLE "UW_WorkflowInstances" ADD "IsCompleted" BIT CONSTRAINT "DF_WorkflowInstances_IsCompleted" DEFAULT ((0)) NOT NULL;
END
GO
UPDATE "UW_WorkflowInstances" set "IsCompleted"=1 WHERE "CurrentState_Id" in (-107,-207,-302,-307,-402,-407,-600) AND IsCompleted=0;
GO
IF COL_LENGTH('dbo.UW_WorkflowInstances', 'WhenCompleted') IS NULL
BEGIN
    ALTER TABLE "UW_WorkflowInstances" ADD "WhenCompleted" DATETIME NULL;
END
GO
